#!/usr/bin/env bash

# when the user is unable to run as a user with elevated privileges,
# we need to let them know. Returns a string for use with 'fail-loud'
#
# returns string
#
# @ error-run-with-root-permissions
error-run-with-root-permissions() {
    local _error=
    local _cmd=

    _cmd="${1:?}"
    _error=<<EOF
It looks like you are running this script as a non-root user.
Please try running again with elevated privileges.
EOF

    echo $_error
}

# sometimes, things happen. No matter how much we try, things happen
# in cases like these, let's let the user know that this is totally
# bizzare, and how to get in contact with us.
#
# returns string
#
# @ error-what-even-happened
error-what-even-happened() {
    local _error=
    local _cmd=

    _cmd="${1:?}"
    _error=<<EOF
Oh my goodness! What on earth even happened here!? No
idea how you got into this situation.
EOF

    echo $_error
}
