#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# adds a prefix to each element in an array
#
# returns string
#
# @ add-prefix-to-each <prefix> <array>
add-prefix-to-each() {
    local _args_array=
    local _arg_len=
    local _prefix=
    local _array=
    local _blob=
    _args_array=($@)
    _arg_len=${#_args_array[@]}
    _prefix="${1:?}"
    _array="${@:2:$_args_len}"

    for element in $_array; do
        _blob="${_blob} ${_prefix} ${element}"
    done

    echo $_blob
}

# Convert any input to lowercase string
#
# returns string
#
# @ to-lowercase <str>
to-lowercase() {
    echo "${1:?}" | tr '[:upper:]' '[:lower:]'
}

replace-string() {
    local _find=
    local _replace=
    local _file=
    local _tmpdir=
    local _tmpfile=
    local _filename=

    _find="${1:?}"
    _replace="${2:?}"
    _file="${3:?}"
    _escaped_find=$(escape-string $_find)
    _escaped_replace=$(escape-string $_replace)
    _filename=$(basename $_file)
    _tmpdir=$(random-tmpdir)
    _tmpfile="${_tmpdir}/${_filename}"

    debug "[replace-string] Making backup of ${_file} to ${_tmpfile}"
    safe-copy $_file $_tmpfile

    debug "[replace-string] Replacing '${_find}' with '${_replace}' in ${_tmpfile}"
    sed -i '' "s/${_escaped_find}/${_escaped_replace}/g" $_tmpfile

    debug "[replace-string] Copying edited file to ${_file}"
    safe-copy $_tmpfile $_file
}

# Thanks to Gurpartap Singh! :bow:
# http://stackoverflow.com/a/10467453
escape-string() {
    local _string=
    _string="${1:?}"

    echo $(echo $_string | sed -e 's/[\/&]/\\&/g')
}
