#!/usr/bin/env bash
#
#  This file is used to bootstrap a project, and may
#  be invocated by the remote system or other scripts
#
#  Should be as OS generic as possible
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/shared-functions


### ADD USER DATA HERE ###

exit 0
