#!/usr/bin/env bash
#
#  This file is used to run CI, and will
#  be invocated by the remote system.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/helpers

setup-test-ldap-server() {
    slapd-setup-test-server
}

destroy-test-ldap-server() {
    local _ldap_server_pid=
    _ldap_server_pid="$(lookup-pid slapd)"

    slapd-server-stop $_ldap_server_pid
}

run-dogma-linter() {
    mix dogma
}

run-tests() {
    mix test
}

init-cibuild() {
    setup-test-ldap-server
#    run-dogma-linter
#    run-tests
#    destroy-test-ldap-server
}

init-cibuild
