#!/usr/bin/env bash
#
#  This file is used to run CI, and will
#  be invocated by the remote system.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/shared-functions

### PUT USER DATA HERE ###

exit 0
