#!/usr/bin/env bash
#
# This file serves as the shared entry point for
# any script in this directory.
#
# To source a script, add the following:
# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# source $DIR/helpers

script-dir() {
    local _dir=
    _dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    echo $_dir
}

file-exists() {
    local _file=
    _file="${1:?}"

    if [ -f $_file ];
    then true;
    else false
    fi
}

source-file() {
    local _file=
    _file="${1:?}"

    if file-exists $_file; then
        source $_file
    fi
}

source-dir() {
    local _dir=
    _dir="${1:?}"

    for file in $(files-in-dir $_dir); do
        source-file $file
    done
}

files-in-dir() {
    local _dir=
    _dir="${1:?}"

    echo $(find $_dir -type f)
}

init-helpers() {
    local _root_dir=
    _root_dir=`cd $(script-dir)/../ && pwd`

    source-file $_root_dir/.env
    source-dir $_root_dir/script/helpers.d
}

init-helpers
