#!/usr/bin/env bash
#
# This file serves as the shared entry point for
# any script in this directory.
#
# To source a script, add the following:
# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# source $DIR/helpers

_script_dir() {
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  echo $DIR
}

_source_file() {
  FILE=$1
  if [ -f $FILE ]; then
    source $FILE
  fi
}

_source_dir() {
  DIR=$1
  for FILE in `find $DIR -type f`; do
    _source_file $FILE
  done
}

## Main
_helper_init() {
  DIR=$1

  # Load up .env pattern
  _source_file $DIR/.env

  # Ensure that all helper functions are sourced
  _source_dir $DIR/script/helpers.d
}

# Entry point -- Load up helpers
ROOT_DIR=`cd $(_script_dir)/../ && pwd`
_helper_init $ROOT_DIR
