#!/usr/bin/env bash
#
# This file serves as the shared entry point for
# any script in this directory.
#
# To source a script, add the following:
# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# source $DIR/shared-functions
_root_dir() {
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../"
  echo $DIR
}

_source_dotenv() {
  DIR=$1
  if [ -f $DIR/.env ]; then
    source $DIR/.env
  fi
}

_os() {
  echo $(uname -s)
}

_rev() {
  echo $(uname -r)
}

_mach() {
  echo $(uname -m)
}

_arch() {
  OS=$1

  if [ "$OS" = "OpenBSD" ]; then
    ARGS="arch -s"
  fi

  echo $(arch ${ARGS})
}

_dist() {
  if [ $# -eq 0 ]; then
    echo "Missing OS"
  else
    OS=$1

    if [ -f /etc/redhat-release ]; then
      DIST='RedHat'
    elif [ -f /etc/SUSE-release ]; then
      DIST=`cat /etc/SUSE-release | tr "\n" ' '| sed s/VERSION.*//`
    elif [ -f /etc/debian_version ] ; then
      DIST="Debian"
    fi

    echo $DIST
  fi
}

_rev() {
  if [ $# -eq 0 ]; then
    echo "Missing DIST"
  else
    DIST=$1

    if [ -f /etc/redhat-release ]; then
      DIST='RedHat'
    elif [ -f /etc/SUSE-release ]; then
      DIST=`cat /etc/SUSE-release | tr "\n" ' '| sed s/VERSION.*//`
    elif [ -f /etc/debian_version ] ; then
      DIST="Debian"
    fi

    echo $REV
  fi
}

_majorver() {
  REV=$1

  echo $(echo ${REV} | cut -d '.' -f1)
}

_codename() {
	if [ -f /etc/debian_version ] ; then
    CODENAME=`/usr/bin/lsb_release -c -s`
  else
    CODENAME="unknown LSB release"
	fi

  echo $CODENAME
}


_init() {
  DIR=$1
  _source_dotenv $DIR
}

# Entry Point for internal scripts
_init $ROOT_DIR
